"""Combine CR channel tables

Revision ID: b854feba6947
Revises: 8e4fea651781
Create Date: 2026-03-04 14:07:36.162778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b854feba6947"
down_revision: Union[str, Sequence[str], None] = "8e4fea651781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cross_resonance_cancellation_channels")
    with op.batch_alter_table("cross_resonance_channels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cross_resonance_channels", schema=None) as batch_op:
        batch_op.drop_column("role")

    op.create_table(
        "cross_resonance_cancellation_channels",
        sa.Column("uuid", sa.CHAR(length=32), nullable=False),
        sa.Column("auxiliary_qubit", sa.INTEGER(), nullable=False),
        sa.Column("frequency", sa.FLOAT(), nullable=True),
        sa.Column("imbalance", sa.FLOAT(), nullable=False),
        sa.Column("phase_iq_offset", sa.FLOAT(), nullable=False),
        sa.Column("scale_real", sa.FLOAT(), nullable=False),
        sa.Column("scale_imag", sa.FLOAT(), nullable=False),
        sa.Column("qubit_uuid", sa.CHAR(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["qubit_uuid"],
            ["qubits.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###
