"""initial_schema

Revision ID: fa934c6fa893
Revises:
Create Date: 2026-03-04 12:37:08.676288

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fa934c6fa893"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
